DROP TABLE PRODUCTO_PEDIDO;
DROP TABLE PEDIDO;
DROP TABLE FACTURA;
DROP TABLE PRODUCTO;
DROP TABLE USUARIO;
DROP TABLE ROL;
DROP TABLE CLIENTE;
DROP TABLE FABRICANTE;

DROP SEQUENCE SEQ_USUARIO;
DROP SEQUENCE SEQ_ROL;
DROP SEQUENCE SEQ_FACTURA;
DROP SEQUENCE SEQ_PRODUCTO;
DROP SEQUENCE SEQ_PEDIDO;


CREATE TABLE ROL (
    ID_ROL NUMBER,
    DESCRIPCION VARCHAR2(255),
    CONSTRAINT PK_ROLE PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER,
    NICK VARCHAR2(255),
    PASSWD VARCHAR2(255),
    ROL_ID NUMBER,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID_ROL)
);

CREATE TABLE CLIENTE (
    DNI VARCHAR2(255),
    NOMBRE VARCHAR2(255),
    DIRECCION VARCHAR2(255),
    EMAIL VARCHAR2(255),
    TELEFONO VARCHAR2(255),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

CREATE TABLE FABRICANTE (
    CIF VARCHAR2(255),
    NOMBRE VARCHAR2(255),
    CLASIFICACION NUMBER,
    CONSTRAINT PK_FABRICANTE PRIMARY KEY (CIF)
);

CREATE TABLE FACTURA (
    ID_FACTURA NUMBER,
    FECHA_EMISION DATE,
    PRECIO_TOTAL NUMBER,
    CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACTURA)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER,
    DESCRIPCION VARCHAR2(255),
    EXISTENCIAS NUMBER,
    PRECIO NUMBER,
    FABRICANTE_CIF VARCHAR2(255),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    FOREIGN KEY (FABRICANTE_CIF) REFERENCES FABRICANTE(CIF)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER,
    FECHA_PEDIDO DATE,
    FECHA_ENTREGA DATE,
    CLIENTE_DNI VARCHAR2(255),
    FACTURA_ID NUMBER,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    FOREIGN KEY (CLIENTE_DNI) REFERENCES CLIENTE(DNI),
    FOREIGN KEY (FACTURA_ID) REFERENCES FACTURA(ID_FACTURA)
);

CREATE TABLE PRODUCTO_PEDIDO (
    ID_PEDIDO NUMBER,
    ID_PRODUCTO NUMBER,
    CONSTRAINT PK_PRODUCTOS_PEDIDOS PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE SEQUENCE SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_ROL
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_FACTURA
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_PRODUCTO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_PEDIDO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
-- Inserts para ROL
INSERT INTO ROL (ID_ROL, DESCRIPCION) VALUES (SEQ_ROL.NEXTVAL, 'Administrador');
INSERT INTO ROL (ID_ROL, DESCRIPCION) VALUES (SEQ_ROL.NEXTVAL, 'Usuario regular');
INSERT INTO ROL (ID_ROL, DESCRIPCION) VALUES (SEQ_ROL.NEXTVAL, 'Gerente');

-- Inserts para USUARIO
INSERT INTO USUARIO (ID_USUARIO, NICK, PASSWD, ROL_ID) VALUES (SEQ_USUARIO.NEXTVAL, 'juan123', 'contraseña1', 1);
INSERT INTO USUARIO (ID_USUARIO, NICK, PASSWD, ROL_ID) VALUES (SEQ_USUARIO.NEXTVAL, 'maria456', 'contraseña2', 2);
INSERT INTO USUARIO (ID_USUARIO, NICK, PASSWD, ROL_ID) VALUES (SEQ_USUARIO.NEXTVAL, 'pedro789', 'contraseña3', 3);

-- Inserts para CLIENTE
INSERT INTO CLIENTE (DNI, NOMBRE, DIRECCION, EMAIL, TELEFONO) VALUES ('1245A', 'Juan Pérez', 'Calle Principal 123', 'juan@example.com', '657234985');
INSERT INTO CLIENTE (DNI, NOMBRE, DIRECCION, EMAIL, TELEFONO) VALUES ('7462H', 'María Gómez', 'Avenida Central 456', 'maria@example.com', '645634789');
INSERT INTO CLIENTE (DNI, NOMBRE, DIRECCION, EMAIL, TELEFONO) VALUES ('7392L', 'Pedro Martínez', 'Plaza Mayor 789', 'pedro@example.com', '606721837');

-- Inserts para FABRICANTE
INSERT INTO FABRICANTE (CIF, NOMBRE, CLASIFICACION) VALUES ('FAB123', 'Mercadona', 1);
INSERT INTO FABRICANTE (CIF, NOMBRE, CLASIFICACION) VALUES ('FAB456', 'Sprinter', 2);
INSERT INTO FABRICANTE (CIF, NOMBRE, CLASIFICACION) VALUES ('FAB789', 'Zara', 3);

-- Inserts para FACTURA
INSERT INTO FACTURA (ID_FACTURA, FECHA_EMISION, PRECIO_TOTAL) VALUES (SEQ_FACTURA.NEXTVAL, TO_DATE('2023-12-01', 'YYYY-MM-DD'), 100.00);
INSERT INTO FACTURA (ID_FACTURA, FECHA_EMISION, PRECIO_TOTAL) VALUES (SEQ_FACTURA.NEXTVAL, TO_DATE('2023-12-02', 'YYYY-MM-DD'), 75.00);
INSERT INTO FACTURA (ID_FACTURA, FECHA_EMISION, PRECIO_TOTAL) VALUES (SEQ_FACTURA.NEXTVAL, TO_DATE('2023-12-03', 'YYYY-MM-DD'), 120.00);

-- Inserts para PRODUCTO
INSERT INTO PRODUCTO (ID_PRODUCTO, DESCRIPCION, EXISTENCIAS, PRECIO, FABRICANTE_CIF) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Pan', 10, 1.00, 'FAB123');
INSERT INTO PRODUCTO (ID_PRODUCTO, DESCRIPCION, EXISTENCIAS, PRECIO, FABRICANTE_CIF) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Deportivas', 15, 70.00, 'FAB456');
INSERT INTO PRODUCTO (ID_PRODUCTO, DESCRIPCION, EXISTENCIAS, PRECIO, FABRICANTE_CIF) VALUES (SEQ_PRODUCTO.NEXTVAL, 'Pantalon', 20, 40.00, 'FAB789');

-- Inserts para PEDIDO
INSERT INTO PEDIDO (ID_PEDIDO, FECHA_PEDIDO, FECHA_ENTREGA, CLIENTE_DNI, FACTURA_ID) VALUES (SEQ_PEDIDO.NEXTVAL, TO_DATE('2023-12-01', 'YYYY-MM-DD'), TO_DATE('2023-12-10', 'YYYY-MM-DD'), '1245A', 1);
INSERT INTO PEDIDO (ID_PEDIDO, FECHA_PEDIDO, FECHA_ENTREGA, CLIENTE_DNI, FACTURA_ID) VALUES (SEQ_PEDIDO.NEXTVAL, TO_DATE('2023-12-02', 'YYYY-MM-DD'), TO_DATE('2023-12-12', 'YYYY-MM-DD'), '7462H', 2);
INSERT INTO PEDIDO (ID_PEDIDO, FECHA_PEDIDO, FECHA_ENTREGA, CLIENTE_DNI, FACTURA_ID) VALUES (SEQ_PEDIDO.NEXTVAL, TO_DATE('2023-12-03', 'YYYY-MM-DD'), TO_DATE('2023-12-15', 'YYYY-MM-DD'), '7392L', 3);  

-- Inserts para PRODUCTO_PEDIDO
INSERT INTO PRODUCTO_PEDIDO (ID_PEDIDO, ID_PRODUCTO) VALUES (1, 1);
INSERT INTO PRODUCTO_PEDIDO (ID_PEDIDO, ID_PRODUCTO) VALUES (1, 2);
INSERT INTO PRODUCTO_PEDIDO (ID_PEDIDO, ID_PRODUCTO) VALUES (2, 2);
INSERT INTO PRODUCTO_PEDIDO (ID_PEDIDO, ID_PRODUCTO) VALUES (3, 3);
INSERT INTO PRODUCTO_PEDIDO (ID_PEDIDO, ID_PRODUCTO) VALUES (3, 1);
